{
  parserClass="org.limepepper.gdb.parser.GdbParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Gdb"
  psiImplClassSuffix="Impl"
  psiPackage="org.limepepper.gdb.psi"
  psiImplPackage="org.limepepper.gdb.psi.impl"

  elementTypeHolderClass="org.limepepper.gdb.psi.GdbTypes"
  elementTypeClass="org.limepepper.gdb.psi.GdbElementType"
  tokenTypeClass="org.limepepper.gdb.psi.GdbTokenType"

  psiImplUtilClass="org.limepepper.gdb.psi.impl.GdbPsiUtil"

tokens = [
  WHITESPACE = 'regexp:\s+'
  NEWLINE = 'regexp:\r\n|\r|\n'
  COMMENT = 'regexp:#.*'
  IDENTIFIER = 'regexp:[a-zA-Z_][a-zA-Z0-9_]*'
  VARIABLE = 'regexp:\$[a-zA-Z_][a-zA-Z0-9_]*'
  NUMBER = 'regexp:\d+'
  STRING = 'regexp:"[^"]*"'

  EQUALS = '='
  COMMA = ','
  LPAREN = '\('
  RPAREN = '\)'
  GREATER = '>'
  LESS = '<'
]

}

// Entry point
root ::= statement*

statement ::= assignment | breakpoint | command_block | command_line

// Assignment: set key = value OR set $var = value
assignment ::= 'set' (VARIABLE | IDENTIFIER) EQUALS value

value ::= VARIABLE | NUMBER | STRING | IDENTIFIER

// Breakpoint with optional condition
breakpoint ::= 'break' IDENTIFIER ( 'if' condition )?

condition ::= expression

expression ::= IDENTIFIER (GREATER | LESS | EQUALS) value

// Block commands
command_block ::= 'commands' NEWLINE command_line* 'end'

// Command line: base command and optional args
command_line ::= command_name arguments?

command_name ::= IDENTIFIER

arguments ::= (value | expression | IDENTIFIER)+

// Comments and blank lines
private comment ::= COMMENT
private blank ::= WHITESPACE | NEWLINE
