"""
GDB Python API stub module for IntelliJ Python plugin support.
This provides type hints and documentation for the gdb module that GDB
automatically imports when running Python scripts.

Based on GDB documentation: https://sourceware.org/gdb/onlinedocs/gdb/Python-API.html
"""

from typing import Optional, List, Dict, Any, Union, Iterator, Callable
from typing_extensions import Literal

# Constants
PYTHONDIR: str
STDOUT: int
STDERR: int  
STDLOG: int

# Core GDB Functions
def execute(command: str, to_string: bool = False, from_tty: bool = False) -> Optional[str]:
    """Execute a GDB CLI command.
    
    Args:
        command: The GDB command to execute
        to_string: If True, return output as string instead of printing
        from_tty: Whether command is from terminal
        
    Returns:
        Command output if to_string=True, None otherwise
    """
    ...

def breakpoints() -> List['Breakpoint']:
    """Return a sequence of all breakpoints."""
    ...

def rbreak(regex: str, minsyms: bool = True, throttle: int = 0, symtabs: Optional[List[str]] = None) -> List['Breakpoint']:
    """Set breakpoints matching a regex pattern."""
    ...

def parameter(parameter_name: str) -> Any:
    """Return the value of a GDB parameter."""
    ...

def set_parameter(parameter_name: str, value: Any) -> None:
    """Set the value of a GDB parameter."""
    ...

def with_parameter(parameter_name: str, value: Any) -> Any:
    """Context manager to temporarily set a parameter."""
    ...

def history(number: int) -> 'Value':
    """Return a value from GDB's value history."""
    ...

def add_history(value: 'Value') -> int:
    """Add a value to the value history."""
    ...

def history_count() -> int:
    """Return the number of values in the value history."""
    ...

def convenience_variable(name: str) -> Optional['Value']:
    """Return the value of a convenience variable."""
    ...

def set_convenience_variable(name: str, value: Any) -> None:
    """Set a convenience variable."""
    ...

def parse_and_eval(expression: str) -> 'Value':
    """Parse and evaluate an expression, returning a Value."""
    ...

def find_pc_line(pc: int) -> Optional['Symtab_and_line']:
    """Find the source line corresponding to a program counter."""
    ...

def write(text: str, stream: Optional[int] = None) -> None:
    """Write text to a GDB output stream."""
    ...

def flush(stream: Optional[int] = None) -> None:
    """Flush a GDB output stream."""
    ...

def warning(text: str) -> None:
    """Print a warning message."""
    ...

def solib_name(address: int) -> Optional[str]:
    """Return the name of the shared library containing address."""
    ...

def decode_line(expression: Optional[str] = None) -> List['Symtab_and_line']:
    """Decode a line specification."""
    ...

def architecture_names() -> List[str]:
    """Return a list of supported architecture names."""
    ...

def connections() -> List['TargetConnection']:
    """Return list of active target connections."""
    ...

def format_address(address: int, prog_space: Optional['Progspace'] = None) -> str:
    """Format an address with symbol information."""
    ...

def current_language() -> str:
    """Return the name of the current language."""
    ...

# Global objects
current_progspace: 'Progspace'
current_objfile: Optional['Objfile']
newest_frame: 'Frame'
selected_frame: 'Frame'
selected_thread: Optional['InferiorThread']
selected_inferior: 'Inferior'

# Classes
class Value:
    """Represents a value in the debugged program."""
    
    def __init__(self, value: Any, type: Optional['Type'] = None) -> None: ...
    
    @property
    def address(self) -> Optional['Value']: ...
    @property
    def is_optimized_out(self) -> bool: ...
    @property
    def type(self) -> 'Type': ...
    @property
    def dynamic_type(self) -> 'Type': ...
    @property
    def is_lazy(self) -> bool: ...
    
    def cast(self, type: 'Type') -> 'Value': ...
    def dereference(self) -> 'Value': ...
    def referenced_value(self) -> 'Value': ...
    def reference_value(self) -> 'Value': ...
    def const_value(self) -> 'Value': ...
    def dynamic_cast(self, type: 'Type') -> 'Value': ...
    def reinterpret_cast(self, type: 'Type') -> 'Value': ...
    def format_string(self, **kwargs) -> str: ...
    def string(self, encoding: Optional[str] = None, errors: str = 'strict', length: Optional[int] = None) -> str: ...
    def lazy_string(self, encoding: Optional[str] = None, length: Optional[int] = None) -> 'LazyString': ...
    def fetch_lazy(self) -> None: ...

class Type:
    """Represents a type in the debugged program."""
    
    @property
    def alignof(self) -> int: ...
    @property
    def code(self) -> int: ...
    @property
    def name(self) -> Optional[str]: ...
    @property
    def sizeof(self) -> int: ...
    @property
    def tag(self) -> Optional[str]: ...
    
    def array(self, n1: int, n2: Optional[int] = None) -> 'Type': ...
    def vector(self, n: int) -> 'Type': ...
    def pointer(self) -> 'Type': ...
    def reference(self) -> 'Type': ...
    def rvalue_reference(self) -> 'Type': ...
    def const(self) -> 'Type': ...
    def volatile(self) -> 'Type': ...
    def unqualified(self) -> 'Type': ...
    def range(self) -> tuple[int, int]: ...
    def target(self) -> 'Type': ...
    def template_argument(self, n: int, block: Optional['Block'] = None) -> Union['Type', 'Value']: ...
    def optimized_out(self) -> 'Value': ...

class Frame:
    """Represents a frame in the call stack."""
    
    @property
    def is_valid(self) -> bool: ...
    @property
    def name(self) -> Optional[str]: ...
    @property
    def architecture(self) -> 'Architecture': ...
    @property
    def type(self) -> int: ...
    @property
    def unwind_stop_reason(self) -> int: ...
    @property
    def pc(self) -> int: ...
    @property
    def block(self) -> 'Block': ...
    @property
    def function(self) -> Optional['Symbol']: ...
    @property
    def older(self) -> Optional['Frame']: ...
    @property
    def newer(self) -> Optional['Frame']: ...
    @property
    def sal(self) -> 'Symtab_and_line': ...
    
    def is_valid(self) -> bool: ...
    def select(self) -> None: ...
    def read_register(self, register: str) -> 'Value': ...
    def read_var(self, variable: Union[str, 'Symbol'], block: Optional['Block'] = None) -> 'Value': ...

class Breakpoint:
    """Represents a breakpoint."""
    
    def __init__(self, spec: str, type: int = ..., wp_class: int = ..., internal: bool = False, temporary: bool = False, qualified: bool = True) -> None: ...
    
    @property
    def enabled(self) -> bool: ...
    @enabled.setter
    def enabled(self, value: bool) -> None: ...
    @property
    def silent(self) -> bool: ...
    @silent.setter  
    def silent(self, value: bool) -> None: ...
    @property
    def pending(self) -> bool: ...
    @property
    def thread(self) -> Optional[int]: ...
    @thread.setter
    def thread(self, value: Optional[int]) -> None: ...
    @property
    def task(self) -> Optional[int]: ...
    @task.setter
    def task(self, value: Optional[int]) -> None: ...
    @property
    def ignore_count(self) -> int: ...
    @ignore_count.setter
    def ignore_count(self, value: int) -> None: ...
    @property
    def number(self) -> int: ...
    @property
    def type(self) -> int: ...
    @property
    def visible(self) -> bool: ...
    @property
    def temporary(self) -> bool: ...
    @property
    def hit_count(self) -> int: ...
    @property
    def location(self) -> Optional[str]: ...
    @property
    def expression(self) -> Optional[str]: ...
    @property
    def condition(self) -> Optional[str]: ...
    @condition.setter
    def condition(self, value: Optional[str]) -> None: ...
    @property
    def commands(self) -> Optional[str]: ...
    @commands.setter
    def commands(self, value: Optional[str]) -> None: ...
    
    def is_valid(self) -> bool: ...
    def delete(self) -> None: ...
    
    def stop(self) -> bool:
        """Called when breakpoint is hit. Return True to stop."""
        ...

class Inferior:
    """Represents an inferior (process being debugged)."""
    
    @property
    def num(self) -> int: ...
    @property
    def connection(self) -> Optional['TargetConnection']: ...
    @property
    def connection_num(self) -> Optional[int]: ...
    @property
    def pid(self) -> int: ...
    @property
    def was_attached(self) -> bool: ...
    @property
    def main_name(self) -> Optional[str]: ...
    @property
    def progspace(self) -> 'Progspace': ...
    @property
    def arguments(self) -> Optional[str]: ...
    @arguments.setter
    def arguments(self, value: Optional[str]) -> None: ...
    @property
    def environment(self) -> Dict[str, str]: ...
    
    def is_valid(self) -> bool: ...
    def threads(self) -> List['InferiorThread']: ...
    def architecture(self) -> 'Architecture': ...
    def read_memory(self, address: int, length: int) -> memoryview: ...
    def write_memory(self, address: int, buffer: bytes, length: Optional[int] = None) -> None: ...
    def search_memory(self, address: int, length: int, pattern: bytes) -> Optional[int]: ...
    def thread_from_handle(self, handle: bytes) -> Optional['InferiorThread']: ...

class InferiorThread:
    """Represents a thread in an inferior."""
    
    @property
    def name(self) -> Optional[str]: ...
    @name.setter
    def name(self, value: Optional[str]) -> None: ...
    @property
    def num(self) -> int: ...
    @property
    def global_num(self) -> int: ...
    @property
    def ptid(self) -> tuple[int, int, int]: ...
    @property
    def inferior(self) -> 'Inferior': ...
    @property
    def details(self) -> Optional[str]: ...
    
    def is_valid(self) -> bool: ...
    def switch(self) -> None: ...
    def is_stopped(self) -> bool: ...
    def is_running(self) -> bool: ...
    def is_exited(self) -> bool: ...
    def handle(self) -> bytes: ...

class Architecture:
    """Represents a processor architecture."""
    
    @property
    def name(self) -> str: ...
    
    def registers(self, reggroup: Optional[str] = None) -> Iterator['RegisterDescriptor']: ...
    def register_groups(self) -> Iterator['RegisterGroup']: ...
    def disassemble(self, start_pc: int, end_pc: Optional[int] = None, count: Optional[int] = None) -> List[Dict[str, Any]]: ...
    def integer_type(self, size: int, signed: bool = True) -> 'Type': ...
    def pointer_type(self, size: Optional[int] = None) -> 'Type': ...

class Block:
    """Represents a lexical block."""
    
    @property
    def start(self) -> int: ...
    @property
    def end(self) -> int: ...
    @property
    def function(self) -> Optional['Symbol']: ...
    @property
    def superblock(self) -> Optional['Block']: ...
    @property
    def global_block(self) -> 'Block': ...
    @property
    def static_block(self) -> 'Block': ...
    @property
    def is_global(self) -> bool: ...
    @property
    def is_static(self) -> bool: ...
    
    def is_valid(self) -> bool: ...

class Symbol:
    """Represents a symbol in the program."""
    
    @property
    def type(self) -> Optional['Type']: ...
    @property
    def symtab(self) -> Optional['Symtab']: ...
    @property
    def line(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def linkage_name(self) -> str: ...
    @property
    def print_name(self) -> str: ...
    @property
    def addr_class(self) -> int: ...
    @property
    def needs_frame(self) -> bool: ...
    @property
    def is_argument(self) -> bool: ...
    @property
    def is_constant(self) -> bool: ...
    @property
    def is_function(self) -> bool: ...
    @property
    def is_variable(self) -> bool: ...
    
    def is_valid(self) -> bool: ...
    def value(self, frame: Optional['Frame'] = None) -> 'Value': ...

class Symtab:
    """Represents a symbol table."""
    
    @property
    def filename(self) -> str: ...
    @property
    def objfile(self) -> 'Objfile': ...
    @property
    def producer(self) -> Optional[str]: ...
    
    def is_valid(self) -> bool: ...
    def fullname(self) -> str: ...
    def global_block(self) -> 'Block': ...
    def static_block(self) -> 'Block': ...
    def linetable(self) -> Optional['LineTable']: ...

class Symtab_and_line:
    """Represents a symtab and line location."""
    
    @property
    def symtab(self) -> Optional['Symtab']: ...
    @property
    def pc(self) -> int: ...
    @property
    def last(self) -> int: ...
    @property
    def line(self) -> int: ...
    
    def is_valid(self) -> bool: ...

class LineTable:
    """Represents a line table."""
    
    def line(self, line: int) -> List['LineTableEntry']: ...
    def is_valid(self) -> bool: ...
    def source_lines(self) -> List[int]: ...

class LineTableEntry:
    """Represents a line table entry."""
    
    @property
    def line(self) -> int: ...
    @property
    def pc(self) -> int: ...

class Objfile:
    """Represents an object file."""
    
    @property
    def filename(self) -> str: ...
    @property
    def username(self) -> Optional[str]: ...
    @property
    def owner(self) -> Optional['Progspace']: ...
    @property
    def build_id(self) -> Optional[str]: ...
    @property
    def progspace(self) -> 'Progspace': ...
    @property
    def pretty_printers(self) -> List[Callable]: ...
    @property
    def type_printers(self) -> List[Callable]: ...
    @property
    def frame_filters(self) -> Dict[str, Callable]: ...
    
    def is_valid(self) -> bool: ...
    def add_separate_debug_file(self, filename: str) -> 'Objfile': ...
    def lookup_global_symbol(self, name: str, domain: Optional[int] = None) -> Optional['Symbol']: ...
    def lookup_static_symbol(self, name: str, domain: Optional[int] = None) -> Optional['Symbol']: ...

class Progspace:
    """Represents a program space."""
    
    @property
    def filename(self) -> Optional[str]: ...
    @property
    def pretty_printers(self) -> List[Callable]: ...
    @property
    def type_printers(self) -> List[Callable]: ...
    @property
    def frame_filters(self) -> Dict[str, Callable]: ...
    
    def is_valid(self) -> bool: ...
    def block_for_pc(self, pc: int) -> Optional['Block']: ...
    def find_pc_line(self, pc: int) -> 'Symtab_and_line': ...
    def objfiles(self) -> Iterator['Objfile']: ...
    def solib_name(self, address: int) -> Optional[str]: ...

class LazyString:
    """Represents a lazy string."""
    
    @property
    def address(self) -> int: ...
    @property
    def length(self) -> int: ...
    @property
    def encoding(self) -> Optional[str]: ...
    @property
    def type(self) -> 'Type': ...
    
    def value(self) -> str: ...

class RegisterDescriptor:
    """Represents a register descriptor."""
    
    @property
    def name(self) -> str: ...

class RegisterGroup:
    """Represents a register group."""
    
    @property
    def name(self) -> str: ...

class TargetConnection:
    """Represents a target connection."""
    
    @property
    def num(self) -> int: ...
    @property
    def type(self) -> str: ...
    @property
    def description(self) -> str: ...
    @property
    def details(self) -> Optional[str]: ...
    
    def is_valid(self) -> bool: ...

# Events - simplified for stub purposes
class Event:
    """Base class for GDB events."""
    pass

class StopEvent(Event):
    """Event fired when inferior stops."""
    pass

class BreakpointEvent(StopEvent):
    """Event fired when a breakpoint is hit."""
    
    @property
    def breakpoints(self) -> List['Breakpoint']: ...

class SignalEvent(StopEvent):
    """Event fired when inferior receives a signal."""
    
    @property
    def stop_signal(self) -> str: ...

class ExitedEvent(Event):
    """Event fired when inferior exits."""
    
    @property
    def exit_code(self) -> Optional[int]: ...

class ContinueEvent(Event):
    """Event fired when inferior continues."""
    pass

class NewObjFileEvent(Event):
    """Event fired when a new object file is loaded."""
    
    @property
    def new_objfile(self) -> 'Objfile': ...

class ClearObjFilesEvent(Event):
    """Event fired when object files are cleared."""
    
    @property
    def progspace(self) -> 'Progspace': ...

class NewInferiorEvent(Event):
    """Event fired when a new inferior is created."""
    
    @property
    def inferior(self) -> 'Inferior': ...

class InferiorDeletedEvent(Event):
    """Event fired when an inferior is deleted."""
    
    @property
    def inferior(self) -> 'Inferior': ...

class NewThreadEvent(Event):
    """Event fired when a new thread is created."""
    
    @property
    def inferior_thread(self) -> 'InferiorThread': ...

# Event registries (simplified)
class EventRegistry:
    """Base event registry."""
    
    def connect(self, callback: Callable[[Event], None]) -> None: ...
    def disconnect(self, callback: Callable[[Event], None]) -> None: ...

events: EventRegistry

# Type constants
TYPE_CODE_PTR: int
TYPE_CODE_ARRAY: int
TYPE_CODE_STRUCT: int
TYPE_CODE_UNION: int
TYPE_CODE_ENUM: int
TYPE_CODE_FLAGS: int
TYPE_CODE_FUNC: int
TYPE_CODE_INT: int
TYPE_CODE_FLT: int
TYPE_CODE_VOID: int
TYPE_CODE_SET: int
TYPE_CODE_RANGE: int
TYPE_CODE_STRING: int
TYPE_CODE_BITSTRING: int
TYPE_CODE_ERROR: int
TYPE_CODE_METHOD: int
TYPE_CODE_METHODPTR: int
TYPE_CODE_MEMBERPTR: int
TYPE_CODE_REF: int
TYPE_CODE_RVALUE_REF: int
TYPE_CODE_CHAR: int
TYPE_CODE_BOOL: int
TYPE_CODE_COMPLEX: int
TYPE_CODE_TYPEDEF: int
TYPE_CODE_NAMESPACE: int
TYPE_CODE_DECFLOAT: int
TYPE_CODE_INTERNAL_FUNCTION: int

# Breakpoint types
BP_BREAKPOINT: int
BP_WATCHPOINT: int
BP_HARDWARE_WATCHPOINT: int
BP_READ_WATCHPOINT: int
BP_ACCESS_WATCHPOINT: int

# Watchpoint classes  
WP_WRITE: int
WP_READ: int
WP_ACCESS: int

# Frame types
NORMAL_FRAME: int
DUMMY_FRAME: int
INLINE_FRAME: int
TAILCALL_FRAME: int
SIGTRAMP_FRAME: int
ARCH_FRAME: int
SENTINEL_FRAME: int

# Symbol domains
SYMBOL_UNDEF_DOMAIN: int
SYMBOL_VAR_DOMAIN: int
SYMBOL_STRUCT_DOMAIN: int
SYMBOL_MODULE_DOMAIN: int
SYMBOL_LABEL_DOMAIN: int
SYMBOL_VARIABLES_DOMAIN: int
SYMBOL_FUNCTIONS_DOMAIN: int
SYMBOL_TYPES_DOMAIN: int

# Address classes
SYMBOL_LOC_UNDEF: int
SYMBOL_LOC_CONST: int
SYMBOL_LOC_STATIC: int
SYMBOL_LOC_REGISTER: int
SYMBOL_LOC_ARG: int
SYMBOL_LOC_REF_ARG: int
SYMBOL_LOC_LOCAL: int
SYMBOL_LOC_TYPEDEF: int
SYMBOL_LOC_LABEL: int
SYMBOL_LOC_BLOCK: int
SYMBOL_LOC_CONST_BYTES: int
SYMBOL_LOC_UNRESOLVED: int
SYMBOL_LOC_OPTIMIZED_OUT: int
SYMBOL_LOC_COMPUTED: int
SYMBOL_LOC_REGPARM_ADDR: int